apiVersion: apps/v1
kind: Deployment
metadata:
  name: federated-training-client
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: federated-training-client
  template:
    metadata:
      labels:
        app: federated-training-client
    spec:
      securityContext:
        fsGroup: 65532
      containers:
        - name: data-preparation
          image: ghcr.io/knows-aggregator/data-preparation:latest
          ports:
            - name: preparation
              containerPort: 8080
          env:
            - name: SOURCES
              value: "REPLACE_WITH_CASE_SLICE_URL"
            - name: DATASET
              value: "accellero"
            - name: EGRESS_UMA_URL
              value: "REPLACE_WITH_EGRESS_UMA_URL"
            - name: DATA_DIR
              value: /app/data
          volumeMounts:
            - name: data
              mountPath: /app/data
        - name: model-training
          image: ghcr.io/knows-aggregator/model-training:latest
          ports:
            - name: training
              containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: EGRESS_UMA_URL
              value: "REPLACE_WITH_EGRESS_UMA_URL"
            - name: DATA_DIR
              value: /app/data
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: federated-training-client-data
